source:
  - changed-files:
      - any-glob-to-any-file: "src/**"

build:
  - changed-files:
      - any-glob-to-any-file:
          - "webpack.config.js"
          - "tsconfig.json"
          - "package.json"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "**/*.md"
